Add error handling.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,18 +30,46 @@ jobs:
       - name: Check all necessary files exist
         shell: bash
         run: |
-          echo -e 'check_exist() {\n\tlocal filename\n\tfor filename; do\n\t\ttest -f "$filename" && continue\n\t\techo -e "\e[1;31m\e[1m$(basename $filename) does not exist - aborting.\e[0m" >&2\n\t\treturn 1\n\tdone\n\treturn 0\n}\ncheck_exist $@' > \
-          "$GITHUB_WORKSPACE/action/bin/check_exist"
+          if \
+            echo -e 'check_exist() {\n\tlocal filename\n\tfor filename; do\n\t\ttest -f "$filename" && continue\n\t\techo -e "\e[1;31m\e[1m$(basename $filename) does not exist - aborting.\e[0m" >&2\n\t\treturn 1\n\tdone\n\treturn 0\n}\ncheck_exist $@' > \
+            "$GITHUB_WORKSPACE/action/bin/check_exist"
+          then
+            if ! chmod +x "$GITHUB_WORKSPACE/action/bin/check_exist" &> /dev/null
+            then
+                echo -e "\e[1;31m\e[1mFailed to mark 'check_exist' binary executable - aborting.\e[0m"
+                exit 1
+            fi
+            echo -e "\e[0;34m\e[1m'check_exist' binary created - proceeding.\e[0m"
+          else
+            echo -e "\e[1;31m\e[1mFailed to create 'check_exist' binary - aborting.\e[0m"
+            exit 1
+          fi
           
-          chmod +x "$GITHUB_WORKSPACE/action/bin/check_exist"
           PATH=$PATH:"$GITHUB_WORKSPACE"/action/bin/
+          echo -e "\e[0;36m\e[1m'PATH' set to include '\$GITHUB_WORKSPACE/action/bin/'\e[0m"
           
           cd "$GITHUB_WORKSPACE"
-          check_exist action/entrypoint.sh action/bin/{copy_pkg.sh,generate-index.sh,set_attr.sh,set_color.sh,set_debug.sh,set_gnupg.sh,setup_pacman.sh,setup_pkgbuild.sh,setup_repo.sh,setup_user.sh,syncweb.sh} pkglist
-
-          chmod +x action/entrypoint.sh action/bin/{copy_pkg.sh,generate-index.sh,set_attr.sh,set_color.sh,set_debug.sh,set_gnupg.sh,setup_pacman.sh,setup_pkgbuild.sh,setup_repo.sh,setup_user.sh,syncweb.sh}
           
-          cp -a "$GITHUB_WORKSPACE/action/entrypoint.sh" "$GITHUB_WORKSPACE/"
+          if \
+            check_exist action/entrypoint.sh action/bin/{copy_pkg.sh,generate-index.sh,set_attr.sh,set_color.sh,set_debug.sh,set_gnupg.sh,setup_pacman.sh,setup_pkgbuild.sh,setup_repo.sh,setup_user.sh,syncweb.sh} pkglist
+          then
+            if ! chmod +x action/entrypoint.sh action/bin/{copy_pkg.sh,generate-index.sh,set_attr.sh,set_color.sh,set_debug.sh,set_gnupg.sh,setup_pacman.sh,setup_pkgbuild.sh,setup_repo.sh,setup_user.sh,syncweb.sh}
+            then
+                echo -e "\e[1;31m\e[1mFailed to mark binary files executable - aborting.\e[0m"
+                exit 1
+            fi
+            echo -e "\e[0;34m\e[1mAll binary files found - proceeding.\e[0m"
+          else
+            echo -e "\e[1;31m\e[1mBinary files missing - aborting.\e[0m"
+            exit 1
+          fi
+          
+          if cp -a "$GITHUB_WORKSPACE/action/entrypoint.sh" "$GITHUB_WORKSPACE/"
+          then echo -e "\e[0;34m\e[1mCopied 'entrypoint.sh' to '\$GITHUB_WORKSPACE' - proceeding.\e[0m"
+          else
+            echo -e "\e[1;31m\e[1mFailed to copy 'entrypoint.sh' to '\$GITHUB_WORKSPACE' - aborting.\e[0m"
+            exit 1
+          fi
       - name: Copy package files using rsync
         shell: bash
         env:
@@ -51,6 +79,7 @@ jobs:
           ENABLE_DEBUG: ${{ vars.ENABLE_DEBUG }}
         run: |
           source "$GITHUB_WORKSPACE/action/bin/set_debug.sh"
+          source "/github/workspace/action/bin/set_color.sh"
           source "$GITHUB_WORKSPACE/action/bin/syncweb.sh"
           rsyncfiles "$REMOTE" "$GITHUB_WORKSPACE/repo/"
       - name: Preserve unmodified packages
