Update infinity.yml
Upload apks as artifact only.

diff --git a/.github/workflows/infinity.yml b/.github/workflows/infinity.yml
--- a/.github/workflows/infinity.yml
+++ b/.github/workflows/infinity.yml
@@ -88,9 +88,9 @@ jobs:
                 -e "s#public static final String USER_AGENT = \".*\";#public static final String USER_AGENT = \"${USER_AGENT}\";#" "${apiutils_file}"  &> $DEBUG_OFF
             ./gradlew assembleRelease &> $DEBUG_OFF
             ./gradlew assembleMinifiedRelease &> $DEBUG_OFF
-            mkdir -pv "${APPDIR}-default"
-            mv -vf "${APPDIR}/app/build/outputs/apk/{minifiedRelease,release}/*.apk" "${APPDIR}-default/" &> $DEBUG_OFF
-            cp -vf "${apiutils_file}" "${APPDIR}-default/" &> $DEBUG_OFF
+            mkdir -pv "${APPDIR}-APK"
+            mv -vf "${APPDIR}/app/build/outputs/apk/{minifiedRelease,release}/*.apk" "${APPDIR}-APK/" &> $DEBUG_OFF
+            cp -vf "${apiutils_file}" "${APPDIR}-APK/" &> $DEBUG_OFF
           else
             printf "${ORANGE_COLOR}NOTE: API_TOKEN not provided, building default apk.${UNSET_COLOR}\n\n"
             ./gradlew assemble &> $DEBUG_OFF
@@ -100,50 +100,57 @@ jobs:
           fi
 
       - uses: actions/upload-artifact@v3
-        name: Upload default APKs as artifact.
+        name: Upload APKs as artifact.
         if: ${{ env.APK_VARIANT_DEFAULT == 'true' }}
         with:
           name: Default APKs
           path: ${{ env.APPDIR }}-default/*.apk
 
-      - name: "Upload compressed APK."
+      - uses: actions/upload-artifact@v3
+        name: Upload APKs as artifact.
         if: ${{ env.APK_VARIANT_DEFAULT != 'true' }}
-        env:
-          SSHKEY: ${{ secrets.SSHKEY }}
-          REMOTE: ${{ secrets.REMOTE_ANDROID }}
-          HOST: ${{ secrets.HOST }}
-        run: |
-          [[ -f ${GITHUB_WORKSPACE}/debug.sh ]] && source ${GITHUB_WORKSPACE}/debug.sh
+        with:
+          name: Infinity APKs
+          path: ${{ env.APPDIR }}-APK/*.ap
 
-          if ! grep -Fxq "$HOST" "/home/runner/.ssh/known_hosts" &> $DEBUG_OFF; then
-            if ! echo "$HOST" | tee -a "/home/runner/.ssh/known_hosts" &> $DEBUG_OFF; then
-              echo -e "${RED_COLOR}${BOLD_TEXT}Failed to append REMOTE to '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}"
-              exit 1
-            fi
-            echo -e "${BLUE_COLOR}${BOLD_TEXT}REMOTE appended to '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}"
+#      - name: "Upload compressed APK."
+#        if: ${{ env.APK_VARIANT_DEFAULT != 'true' }}
+#        env:
+#          SSHKEY: ${{ secrets.SSHKEY }}
+#          REMOTE: ${{ secrets.REMOTE_ANDROID }}
+#          HOST: ${{ secrets.HOST }}
+#        run: |
+#          [[ -f ${GITHUB_WORKSPACE}/debug.sh ]] && source ${GITHUB_WORKSPACE}/debug.sh
 
-            chmod -v 0600 "/home/runner/.ssh/known_hosts" &> $DEBUG_OFF && \
-              echo -e "${BLUE_COLOR}${BOLD_TEXT}Corrected permissions of '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}" || \
-                (echo -e "${RED_COLOR}${BOLD_TEXT}Failed to set correct permissions of '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}" \
-                  && exit 1 )
-          fi
+#          if ! grep -Fxq "$HOST" "/home/runner/.ssh/known_hosts" &> $DEBUG_OFF; then
+#            if ! echo "$HOST" | tee -a "/home/runner/.ssh/known_hosts" &> $DEBUG_OFF; then
+#              echo -e "${RED_COLOR}${BOLD_TEXT}Failed to append REMOTE to '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}"
+#              exit 1
+#            fi
+#            echo -e "${BLUE_COLOR}${BOLD_TEXT}REMOTE appended to '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}"
 
-          if [[ -f "/home/runner/.ssh/id_ed25519" ]]; then
-            echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519.bak" &> $DEBUG_OFF
-            if ! diff "/home/runner/.ssh/id_ed25519" "/home/runner/.ssh/id_ed25519.bak" &> $DEBUG_OFF; then
-              mv -v "/home/runner/.ssh/id_ed25519.bak" "/home/runner/.ssh/id_ed25519" &> $DEBUG_OFF
-              echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
-            fi
-          else
-            echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519" &> $DEBUG_OFF
-            echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
-          fi
+#            chmod -v 0600 "/home/runner/.ssh/known_hosts" &> $DEBUG_OFF && \
+#              echo -e "${BLUE_COLOR}${BOLD_TEXT}Corrected permissions of '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}" || \
+#                (echo -e "${RED_COLOR}${BOLD_TEXT}Failed to set correct permissions of '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}" \
+#                  && exit 1 )
+#          fi
 
-          chmod -v 0600 "/home/runner/.ssh/id_ed25519" &> $DEBUG_OFF
+#          if [[ -f "/home/runner/.ssh/id_ed25519" ]]; then
+#            echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519.bak" &> $DEBUG_OFF
+#            if ! diff "/home/runner/.ssh/id_ed25519" "/home/runner/.ssh/id_ed25519.bak" &> $DEBUG_OFF; then
+#              mv -v "/home/runner/.ssh/id_ed25519.bak" "/home/runner/.ssh/id_ed25519" &> $DEBUG_OFF
+#              echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
+#            fi
+#          else
+#            echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519" &> $DEBUG_OFF
+#            echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
+#          fi
 
-          if rsync -a --delete -e "ssh -v -i /home/runner/.ssh/id_ed25519" "$GITHUB_WORKSPACE/repo/" "$REMOTE" &> $DEBUG_OFF; then
-            echo -e "${BLUE_COLOR}${BOLD_TEXT}Successfully synced files - proceeding.{UNSET_COLOR}"
-          else
-            echo -e "${RED_COLOR}${BOLD_TEXT}Failed to sync files - aborting.${UNSET_COLOR}"
-            return 1
-          fi || (exit 1)
+#          chmod -v 0600 "/home/runner/.ssh/id_ed25519" &> $DEBUG_OFF
+
+#          if rsync -a --delete -e "ssh -v -i /home/runner/.ssh/id_ed25519" "$GITHUB_WORKSPACE/repo/" "$REMOTE" &> $DEBUG_OFF; then
+#            echo -e "${BLUE_COLOR}${BOLD_TEXT}Successfully synced files - proceeding.{UNSET_COLOR}"
+#          else
+#            echo -e "${RED_COLOR}${BOLD_TEXT}Failed to sync files - aborting.${UNSET_COLOR}"
+#            return 1
+#          fi || (exit 1)
