try debug build

diff --git a/.github/workflows/infinity.yml b/.github/workflows/infinity.yml
--- a/.github/workflows/infinity.yml
+++ b/.github/workflows/infinity.yml
@@ -2,7 +2,7 @@ name: Build Infinity
 
 on:
   workflow_dispatch:
-  
+
 env:
   # JAVA_HOME = /usr/lib/jvm/temurin-11-jdk-amd64
   # ANDROID_SDK_ROOT = /usr/local/lib/android/sdk
@@ -12,7 +12,7 @@ env:
   REDIRECT_URL: 'http://127.0.0.1'
   API_TOKEN: ${{ secrets.API_TOKEN-INFINITY }}
   USER_AGENT: "android:github_ci-app:0.${{ github.run_number }}.${{ github.run_attempt }} built by ${{ github.actor }}"
-    # setup colors
+  # setup colors
   RED_COLOR: "\e[1;31m"
   ORANGE_COLOR: "\e[1;33m"
   BLUE_COLOR: "\e[0;34m"
@@ -25,10 +25,10 @@ permissions:
 jobs:
   build_job:
     runs-on: ubuntu-22.04
-    name: Build Infinity for reddit.
+    name: "Build Infinity for reddit."
 
     steps:
-      - name: Set-up PATH and update runner.
+      - name: "Set-up PATH and update runner."
         shell: bash
         run: |
           echo "/usr/local/lib/android/sdk/tools/bin:/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_PATH
@@ -36,12 +36,10 @@ jobs:
 
           sudo apt-get --quiet update
           sudo apt-get --quiet upgrade
-          
-          env
-          
-          yes | sdkmanager  --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-33" "build-tools;33.0.0"
-        
-      - name: Checkout Infinity-For-Reddit repository.
+
+          sdkmanager  --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-33" "build-tools;33.0.0"
+
+      - name: "Checkout Infinity-For-Reddit repository."
         if: ${{ env.VARIANT == 'git' }}
         uses: actions/checkout@v4
         with:
@@ -49,8 +47,8 @@ jobs:
           show-progress: false
           repository: ${{ env.REPO }}
 
-      - name: Fetch source archive.
-        if: ${{ env.VARIANT != 'git' }}
+      - name: "Fetch source archive."
+        if: ${{ env.VARIANT != 'git' }} && ${{  }}
         shell: bash
         run: |
           printf "${RED_COLOR}[IMPORTANT]\n"
@@ -58,10 +56,75 @@ jobs:
 
           latest_tag=$(curl -s "https://api.github.com/repos/${REPO}/releases/latest" \
             | grep "\"tag_name\":" | cut -d \" -f 4)
-              
+
           latest_url="https://github.com/${REPO}/archive/refs/tags/${latest_tag}.tar.gz"
-            
+
           wget --quiet -O "${REPO#*/}.tar.gz" "${latest_url}" && \
           tar xf  "${REPO#*/}.tar.gz" && \
           mv "${REPO#*/}-${latest_tag#*v}" "${REPO#*/}" && \
           rm -f "${REPO#*/}.tar.gz"
+
+          echo "APK_RELEASE_VERSION='RELEASE'" >> "$GITHUB_ENV"
+
+      - name: "Set Release version for git builds."
+        if: ${{ env.VARIANT == 'git' }}
+        shell: bash
+        run: |
+          echo "APK_RELEASE_VERSION='GIT'" >> "$GITHUB_ENV"
+
+      - name: "Build source and compress APKs."
+        shell: bash
+        run: |
+          if [[ -n "${API_TOKEN}" ]]; then
+            sed -i -e "s#\"NOe2iKrPPzwscA\"#\"${API_TOKEN}\"#" \
+                -e "s#\"infinity://localhost\"#\"${REDIRECT_URL}\"#" \
+                -e "s#public static final String USER_AGENT = \".*\";#public static final String USER_AGENT = \"${USER_AGENT}\";#" "${apiutils_file}"
+          #TODO: Compress APKs.
+          else
+            printf "${RED_COLOR}[IMPORTANT]\n"
+            printf "API_TOKEN not provided building debug apk.${UNSET_COLOR}\n"
+            ./gradlew assembledebug
+            echo "APK_VARIANT_DEBUG='true'" >> "$GITHUB_ENV"
+          fi
+
+      - name: "Upload compressed APK."
+        if: ${{ env.APK_VARIANT_DEBUG != 'true' }}
+        uses: actions/upload-release-asset@v1
+        env:
+          SSHKEY: ${{ secrets.SSHKEY }}
+          REMOTE: ${{ secrets.REMOTE_ANDROID }}
+          HOST: ${{ secrets.HOST }}
+        shell: bash
+        run: |
+        if ! grep -Fxq "$HOST" "/home/runner/.ssh/known_hosts"; then
+          if ! echo "$HOST" | tee -a "/home/runner/.ssh/known_hosts" &> /dev/null; then
+            echo -e "${RED_COLOR}${BOLD_TEXT}Failed to append REMOTE to '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}"
+            exit 1
+          fi
+          echo -e "${BLUE_COLOR}${BOLD_TEXT}REMOTE appended to '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}"
+
+          chmod -v 0600 "/home/runner/.ssh/known_hosts" &> /dev/null && \
+            echo -e "${BLUE_COLOR}${BOLD_TEXT}Corrected permissions of '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}" || \
+            ( echo -e "${RED_COLOR}${BOLD_TEXT}Failed to set correct permissions of '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}" && \
+              exit 1 )
+        fi
+
+        if [[ -f "/home/runner/.ssh/id_ed25519" ]]; then
+          echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519.bak" &> /dev/null
+          if ! diff "/home/runner/.ssh/id_ed25519" "/home/runner/.ssh/id_ed25519.bak" &> /dev/null; then
+            mv -v "/home/runner/.ssh/id_ed25519.bak" "/home/runner/.ssh/id_ed25519" &> /dev/null
+            echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
+          fi
+        else
+          echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519" &> /dev/null
+          echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
+        fi
+
+        chmod -v 0600 "/home/runner/.ssh/id_ed25519" &> /dev/null
+
+        if rsync -a --delete -e "ssh -v -i /home/runner/.ssh/id_ed25519" "$GITHUB_WORKSPACE/repo/" "$REMOTE" &> /dev/null; then
+          echo -e "${BLUE_COLOR}${BOLD_TEXT}Successfully synced files - proceeding.{UNSET_COLOR}"
+        else
+          echo -e "${RED_COLOR}${BOLD_TEXT}Failed to sync files - aborting.${UNSET_COLOR}"
+          return 1
+        fi || (exit 1)
