correct yml formatting

diff --git a/.github/workflows/infinity.yml b/.github/workflows/infinity.yml
--- a/.github/workflows/infinity.yml
+++ b/.github/workflows/infinity.yml
@@ -96,35 +96,35 @@ jobs:
           HOST: ${{ secrets.HOST }}
         shell: bash
         run: |
-        if ! grep -Fxq "$HOST" "/home/runner/.ssh/known_hosts"; then
-          if ! echo "$HOST" | tee -a "/home/runner/.ssh/known_hosts" &> /dev/null; then
-            echo -e "${RED_COLOR}${BOLD_TEXT}Failed to append REMOTE to '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}"
-            exit 1
+          if ! grep -Fxq "$HOST" "/home/runner/.ssh/known_hosts"; then
+            if ! echo "$HOST" | tee -a "/home/runner/.ssh/known_hosts" &> /dev/null; then
+              echo -e "${RED_COLOR}${BOLD_TEXT}Failed to append REMOTE to '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}"
+              exit 1
+            fi
+            echo -e "${BLUE_COLOR}${BOLD_TEXT}REMOTE appended to '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}"
+
+            chmod -v 0600 "/home/runner/.ssh/known_hosts" &> /dev/null && \
+              echo -e "${BLUE_COLOR}${BOLD_TEXT}Corrected permissions of '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}" || \
+                (echo -e "${RED_COLOR}${BOLD_TEXT}Failed to set correct permissions of '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}" \
+                  && exit 1 )
           fi
-          echo -e "${BLUE_COLOR}${BOLD_TEXT}REMOTE appended to '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}"
 
-          chmod -v 0600 "/home/runner/.ssh/known_hosts" &> /dev/null && \
-            echo -e "${BLUE_COLOR}${BOLD_TEXT}Corrected permissions of '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}" || \
-            ( echo -e "${RED_COLOR}${BOLD_TEXT}Failed to set correct permissions of '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}" && \
-              exit 1 )
-        fi
-
-        if [[ -f "/home/runner/.ssh/id_ed25519" ]]; then
-          echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519.bak" &> /dev/null
-          if ! diff "/home/runner/.ssh/id_ed25519" "/home/runner/.ssh/id_ed25519.bak" &> /dev/null; then
-            mv -v "/home/runner/.ssh/id_ed25519.bak" "/home/runner/.ssh/id_ed25519" &> /dev/null
+          if [[ -f "/home/runner/.ssh/id_ed25519" ]]; then
+            echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519.bak" &> /dev/null
+            if ! diff "/home/runner/.ssh/id_ed25519" "/home/runner/.ssh/id_ed25519.bak" &> /dev/null; then
+              mv -v "/home/runner/.ssh/id_ed25519.bak" "/home/runner/.ssh/id_ed25519" &> /dev/null
+              echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
+            fi
+          else
+            echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519" &> /dev/null
             echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
           fi
-        else
-          echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519" &> /dev/null
-          echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
-        fi
 
-        chmod -v 0600 "/home/runner/.ssh/id_ed25519" &> /dev/null
+          chmod -v 0600 "/home/runner/.ssh/id_ed25519" &> /dev/null
 
-        if rsync -a --delete -e "ssh -v -i /home/runner/.ssh/id_ed25519" "$GITHUB_WORKSPACE/repo/" "$REMOTE" &> /dev/null; then
-          echo -e "${BLUE_COLOR}${BOLD_TEXT}Successfully synced files - proceeding.{UNSET_COLOR}"
-        else
-          echo -e "${RED_COLOR}${BOLD_TEXT}Failed to sync files - aborting.${UNSET_COLOR}"
-          return 1
-        fi || (exit 1)
+          if rsync -a --delete -e "ssh -v -i /home/runner/.ssh/id_ed25519" "$GITHUB_WORKSPACE/repo/" "$REMOTE" &> /dev/null; then
+            echo -e "${BLUE_COLOR}${BOLD_TEXT}Successfully synced files - proceeding.{UNSET_COLOR}"
+          else
+            echo -e "${RED_COLOR}${BOLD_TEXT}Failed to sync files - aborting.${UNSET_COLOR}"
+            return 1
+          fi || (exit 1)
