Update ocrmypdf.yml

diff --git a/.github/workflows/ocrmypdf.yml b/.github/workflows/ocrmypdf.yml
--- a/.github/workflows/ocrmypdf.yml
+++ b/.github/workflows/ocrmypdf.yml
@@ -29,142 +29,77 @@ jobs:
         if: ${{ runner.debug == '1' }}
         run: |
           set -x
-          echo -e "set -x\nexport DEBUG_OFF='/dev/stdout'" > ${GITHUB_WORKSPACE}/debug.sh
+          echo -e "set -x\nexport DEBUG_OFF='/dev/stdout'" > $HOME/debug.sh
 
-      - name: "Set-up PATH and update build tools."
+      - name: "Set-up PATH and update tools."
         run: |
-          [[ -f "${GITHUB_WORKSPACE}/debug.sh" ]] && source "${GITHUB_WORKSPACE}/debug.sh"
+          [[ -f "$HOME/debug.sh" ]] && source "$HOME/debug.sh"
 
           echo "/usr/bin:/usr/sbin:/bin:/sbin" >> $GITHUB_PATH
 
-          sudo dny --yes upgrade &> $DEBUG_OFF
-          sudo dnf --yes install ocrmypdf &> $DEBUG_OFF
+          sudo dnf --yes upgrade &> $DEBUG_OFF
+          sudo dnf --yes install ocrmypdf jq &> $DEBUG_OFF
 
           echo "keyserver hkps://keys.openpgp.org" > \
-            tee "~/.gnupg/gpg.conf" &> $DEBUG_OFF
+            tee "$HOME/.gnupg/gpg.conf" &> $DEBUG_OFF
+          mkdir "$HOME/enc"
 
-      - name: "Get latest binary."
+      - name: "Get File(s)."
+        env:
+          URL: ${{ vars.URL }}
+          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
+          KEY_FINGERPRINT: ${{ secrets.KEY_FINGERPRINT }}
+          PASSPHRASE: ${{ secrets.PASSPHRASE }}
         run: |
-          [[ -f "${GITHUB_WORKSPACE}/debug.sh" ]] && source "${GITHUB_WORKSPACE}/debug.sh"
+          [[ -f "$HOME/debug.sh" ]] && source "$HOME/debug.sh"
 
-          ftp_server="https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/"
+          cd "$HOME/enc"
 
-          firefox_pipeline=$(curl ${ftp_server} | \
-            grep "en-US.linux-x86_64.checksums" | \
-              sed 's/^.*>firefox-//;s/\.en-US.*//' | sort -n | tail -n 1)
-              
-          build_id=$(curl ${ftp_server}firefox-${firefox_pipeline}.en-US.linux-x86_64_info.txt | grep "^buildID" | cut -d= -f2)
+          wget --content-disposition "${URL}" &> $DEBUG_OFF || \
+            (echo -e "${RED_COLOR}${BOLD_TEXT}Failed to download file - aborting." && exit 1)
 
-          pipeline_id="${build_id:2:2}${build_id:4:4}.${build_id:8:4}"
-          build_date="${build_id:0:4}-${build_id:4:2}-${build_id:6:2}"
+          while ! gpg --list-secret-key | grep "$KEY_FINGERPRINT" &> $DEBUG_OFF; do
+            echo -e "$PRIVATE_KEY" | gpg --batch --import &> $DEBUG_OFF
+          done
 
-          version="${firefox_pipeline}.${pipeline_id}"
-          echo "version=$version" >> $GITHUB_ENV
+          echo"${PASSPHRASE}" | gpg --pinentry-mode loopback \
+            --passphrase-fd 0  --decrypt-files "$HOME/enc/"*.pdf.gpg &> $DEBUG_OFF || \
+            ( echo -e "${RED_COLOR}${BOLD_TEXT}Failed to decrypt file - aborting." && exit 1 )
 
-          download_url="${ftp_server}firefox-${firefox_pipeline}.en-US.linux-x86_64.tar.bz2"
-
-          filename="firefox-${firefox_pipeline}.en-US.linux-x86_64.tar.bz2"
-
-          cd "${GITHUB_WORKSPACE}/flatpak/${APP}"
-
-          curl -o ${filename}.asc ${download_url}.asc \
-            -o ${filename} ${download_url} &> $DEBUG_OFF
-
-          gpg --import KEY.gpg &> $DEBUG_OFF
-
-          gpg --verify ${filename}.asc ${filename} &> $DEBUG_OFF || \
-            ( echo -e "${RED_COLOR}${BOLD_TEXT}Firefox binary not verified - aborting." && exit 1 )
-
-          sed -i "s/XversionX/${version}/;s/XdateX/${build_date}/" \
-            "${APP}.appdata.xml" &> $DEBUG_OFF
-
-          sed -i "s/XversionX/${version}/" "distribution.ini" &> $DEBUG_OFF
-
-          sed -i \
-           -e "s/Xbinary_sha256X/$(sha256sum ${filename} | awk '{ printf $1 }')/" \
-           -e "s/XversionX/${firefox_pipeline}/" \
-           -e "s/Xappdata_sha256X/$(sha256sum ${APP}.appdata.xml | awk '{ printf $1 }')/" \
-           -e "s/Xdistrib_sha256X/$(sha256sum distribution.ini | awk '{ printf $1 }')/" \
-           "${APP}.yaml" &> $DEBUG_OFF
-
-      - name: "Compile Firefox Nightly flatpak bundle."
+      - name: "OCR File(s)."
         run: |
-          [[ -f "${GITHUB_WORKSPACE}/debug.sh" ]] && source "${GITHUB_WORKSPACE}/debug.sh"
+          [[ -f "$HOME/debug.sh" ]] && source "$HOME/debug.sh"
 
-          cd "${GITHUB_WORKSPACE}/flatpak/${APP}"
+          cd  "$HOME/enc"
+          mkdir tmp output
+          export TMPDIR=tmp
 
-          flatpak-builder --repo=nightly build \
-            "${APP}".yaml --force-clean --user --install &> $DEBUG_OFF
+          for pdf_file in *.pdf; do
+          parallel --tag -j 2 ocrmypdf --sidecar 'output/{}'.txt --deskew \
+            --optimize 1 '{}' 'output/{}' ::: "${pdf_file}" &> $DEBUG_OFF
+          done
 
-          flatpak build-bundle nightly --arch=x86_64 \
-            --runtime-repo=https://dl.flathub.org/repo/flathub.flatpakrepo \
-            "${GITHUB_WORKSPACE}/${APP}-${version}.x86_64.flatpak" "${APP}" &> $DEBUG_OFF
-
-      - name: "Sign flatpak bundle."
+      - name: "Encrypt PDF File(s)."
         env:
           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
           PASSPHRASE: ${{ secrets.PASSPHRASE }}
+          KEY_FINGERPRINT: ${{ secrets.KEY_FINGERPRINT }}
         run: |
-          [[ -f "${GITHUB_WORKSPACE}/debug.sh" ]] && source "${GITHUB_WORKSPACE}/debug.sh"
+          [[ -f "$HOME/debug.sh" ]] && source "$HOME/debug.sh"
 
-          cd "${GITHUB_WORKSPACE}/flatpak/${APP}"
+          cd  "$HOME/enc"
 
-          echo -e "${PRIVATE_KEY}" | gpg --batch --import &> $DEBUG_OFF
-          echo "${PASSPHRASE}" | gpg --detach-sign --pinentry-mode loopback \
-            --passphrase --passphrase-fd 0 --sign \
-              "${GITHUB_WORKSPACE}/${APP}-${version}.x86_64.flatpak" &> /dev/null && echo "Signed ${APP}-${version}.x86_64.flatpak"
+          tar -C "$HOME/enc/output" -cf "output.tar.gz" . &> $DEBUG_OFF
 
-          mkdir -vp "${GITHUB_WORKSPACE}/${APP}-${version}" &> $DEBUG_OFF
-          mv -t "${GITHUB_WORKSPACE}/${APP}-${version}/" \
-            "${GITHUB_WORKSPACE}/${APP}-${version}.x86_64.flatpak" \
-            "${GITHUB_WORKSPACE}/${APP}-${version}.x86_64.flatpak.sig"
-          echo "${version}" > "${GITHUB_WORKSPACE}/${APP}-${version}/VERSION"
+          gpg --always-trust -er "${KEY_FINGERPRINT}" -o "output.tar.gz.gpg" "output.tar.gz" || \
+            (echo -e "${RED_COLOR}${BOLD_TEXT}Failed to encrypt file - aborting." && exit 1)
 
-      - name: "Upload Flatpak."
-        env:
-          SSHKEY: ${{ secrets.SSHKEY }}
-          REMOTE: ${{ secrets.REMOTE }}
-          HOST: ${{ secrets.HOST }}
+      - name: "Upload File."
         run: |
-          [[ -f "${GITHUB_WORKSPACE}/debug.sh" ]] && source "${GITHUB_WORKSPACE}/debug.sh"
+          [[ -f "$HOME/debug.sh" ]] && source "$HOME/debug.sh"
 
-          [[ -f "/home/runner/.ssh/known_hosts" ]] && \
-            rm "/home/runner/.ssh/known_hosts" && return 1 || \
-              ( mkdir -p "/home/runner/.ssh" && touch "/home/runner/.ssh/known_hosts" )
+          cd  "$HOME/enc"
 
-          echo "$HOST" | tee -a "/home/runner/.ssh/known_hosts" &> $DEBUG_OFF || \
-            ( echo -e "${RED_COLOR}${BOLD_TEXT}Failed to append REMOTE to '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}" \
-              && exit 1 )
-
-          echo -e "${BLUE_COLOR}${BOLD_TEXT}REMOTE appended to '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}"
-
-          chmod -v 0600 "/home/runner/.ssh/known_hosts" &> $DEBUG_OFF && \
-            echo -e "${BLUE_COLOR}${BOLD_TEXT}Corrected permissions of '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}" || \
-              ( echo -e "${RED_COLOR}${BOLD_TEXT}Failed to set correct permissions of '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}" \
-                && exit 1 )
-
-          [[ -f "/home/runner/.ssh/id_ed25519" ]] && rm "/home/runner/.ssh/id_ed25519" && return 1 || touch "/home/runner/.ssh/known_hosts"
-
-          echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519" &> /dev/null || \
-            ( echo -e "${RED_COLOR}${BOLD_TEXT}Failed to write ssh private key' - aborting.${UNSET_COLOR}" \
-              && exit 1 )
-
-          chmod -v 0600 "/home/runner/.ssh/id_ed25519" &> $DEBUG_OFF
-
-          PROJECT=${REMOTE##*project-web\/}
-          PROJECT=${PROJECT%%\/htdocs*}
-
-          preserve=$(curl -sf -L https://$PROJECT.sourceforge.io/flatpak | grep --color=never -o "<a [A-Za-z]*=.*flatpak\">" | cut -d'"' -f2 | tail -5 | xargs)
-
-          for flatpak_file in ${preserve}; do
-            wget --directory-prefix="${GITHUB_WORKSPACE}/${APP}-${version}/" https://$PROJECT.sourceforge.io/flatpak/"${flatpak_file}"{,.sig} &> $DEBUG_OFF \
-              && gpg --verify "${flatpak_file}.sig" "${flatpak_file}" &> $DEBUG_OFF || (echo -e "${RED_COLOR}${flatpak_file} failed integrity check - removing file." && rm -f ${flatpak_file}{,.sig})
+          while ! curl -F "file=@output.tar.gz.gpg" https://file.io | jq >> "${GITHUB_STEP_SUMMARY}"; do
+            echo -e "${ORANGE_COLOR}${BOLD_TEXT}Failed to encrypt file - retrying.${UNSET_COLOR}"
           done
-
-          if rsync -a --delete -e "ssh -v -i /home/runner/.ssh/id_ed25519" \
-                "${GITHUB_WORKSPACE}/${APP}-${version}/" "${REMOTE}/flatpak/" &> $DEBUG_OFF; then
-            echo -e "${BLUE_COLOR}${BOLD_TEXT}Successfully synced files - proceeding.{UNSET_COLOR}"
-          else
-            echo -e "${RED_COLOR}${BOLD_TEXT}Failed to sync files - aborting.${UNSET_COLOR}"
-            exit 1
-          fi || (exit 1)
